### ISSUE TITLE
panasonic_ems2.py不起作用

### ISSUE THREAD

**Issue by Henrylin923** [tsunglung/panasonic_ems2#2]
有安裝了python
但是執行
python panasonic_ems2.py
沒反應
不知道是哪裡錯誤
方便的話求指點

**Comment by tsunglung** [comment]
What is your environment? Windows?

**Comment by Henrylin923** [comment]
您好
是
Win11 Pro 23H2
我找到原因了
pip install requests
執行完這個就可以

**Comment by Henrylin923** [comment]
[panasonic_commands.json](https://github.com/user-attachments/files/15592480/panasonic_commands.json)
[panasonic_devices.json](https://github.com/user-attachments/files/15592481/panasonic_devices.json)
這個是我的裝置時常不能控制
原廠APP是OK的
